export const seedPositions = [
  { ticker:"SLS", name:"Sellas Life Sciences", exchange:"NASDAQ USD", currency:"USD", shares:200, average_cost:2.83, current_price:7.78, status:"binary", catalyst:"REGAL readout IMMINENT", thesis:"REGAL Phase 3 AML trial at 78/80 events. CEO said very good chance of positive outcome. Readout weeks away. $107M cash, minimal debt.", exit_rule:"Sell 100 shares on positive spike. Hold 100 for FDA submission catalyst. Stop loss at $4 if negative." },
  { ticker:"AMC", name:"AMC Entertainment", exchange:"NYSE USD", currency:"USD", shares:3223.61, average_cost:6.622, current_price:1.515, status:"hold", catalyst:"Q2/Q3 box office results", thesis:"Q2 2026 box office tracking near 2018/2019 record pace. Per-patron spend +61% since 2019. Debt refinanced to 2031. Short squeeze potential if box office sustains.", exit_rule:"SELL 1,000 at $3.00, 1,000 at $5.00, 1,223 at $6.50. Limit orders set in broker." },
  { ticker:"CAN", name:"Canaan Inc", exchange:"NASDAQ USD", currency:"USD", shares:1478, average_cost:0.5468, current_price:0.415, status:"watch", catalyst:"CLARITY Act vote early June", thesis:"CLARITY Act Senate floor vote targeting July 4. CEO+CFO bought at $0.51. Bitcoin at $91K+. NASDAQ delisting deadline July 13.", exit_rule:"Hold to July 4. If CLARITY passes and CAN hits $1.00, sell 50%. Exit entirely by July 14 if still below $1.00." },
  { ticker:"INFQ.WS", name:"Infleqtion Warrants", exchange:"NYSE USD", currency:"USD", shares:50, average_cost:9.1016, current_price:8.32, status:"hold", catalyst:"Federal quantum grants", thesis:"$2B US quantum grant program LOI. Neutral atom architecture. $11.50 strike. 2031 expiry equals full thesis runway. Defense plus commercial quantum.", exit_rule:"Hold 24 months minimum. DCA below $6. Sell only if thesis breaks." },
  { ticker:"ARAAF", name:"Aclara Resources", exchange:"OTC USD", currency:"USD", shares:50, average_cost:3.7122, current_price:3.1641, status:"hold", catalyst:"Penco permit decision", thesis:"$1.7B NPV Carina FS confirmed April 2026. Virginia pilot plant producing REOs now. Heavy rare earths for defense and EV.", exit_rule:"Hold. Do not add near analyst consensus. Wait for Penco permit before reassessing size." },
  { ticker:"BB", name:"BlackBerry", exchange:"TSX CAD", currency:"CAD", shares:45.4181, average_cost:7.61, current_price:8.62, status:"hold", catalyst:"June 25 earnings", thesis:"QNX record revenue +20% YoY. $950M royalty backlog. NVIDIA physical AI partnership. FedRAMP Class D. In profit.", exit_rule:"Hold through June 25. Strong beat hold/add. Disappointment take the profit." },
  { ticker:"FDY", name:"Faraday Copper", exchange:"TSX CAD", currency:"CAD", shares:149.8443, average_cost:4.42, current_price:5.98, status:"add", catalyst:"BHP definitive deal Q3 2026", thesis:"BHP+Lundin invested at CAD$4.20. Definitive San Manuel deal targeting Q3 2026. $120M cash, zero debt. Copper is backbone of AI, EV, and defense.", exit_rule:"Do not sell below $8. Core position. Sell 25% at $8, another 25% at $10." },
  { ticker:"GRSL", name:"GR Silver Mining", exchange:"TSX-V CAD", currency:"CAD", shares:927.0337, average_cost:0.49, current_price:0.44, status:"hold", catalyst:"MRE update + PEA H2 2026", thesis:"Best-ever drill results May 19: 45.1m at 1,623 g/t Ag, bonanza 8,579 g/t interval. $28.8M cash, zero debt. PEA unlocks institutions.", exit_rule:"Hold through PEA late 2026. PEA result is the decision gate." },
  { ticker:"PNG", name:"Kraken Robotics", exchange:"TSX-V CAD", currency:"CAD", shares:54.0408, average_cost:8.45, current_price:7.69, status:"watch", catalyst:"June 3 earnings IMMINENT", thesis:"Covelya $615M acquisition. $52M orders YTD. Subsea defense sonar plus SeaPower batteries. $10.80 analyst target vs $7.69.", exit_rule:"Hold through June 3. Strong equals add to 150+ shares. Miss equals reassess entire position." },
  { ticker:"TMQ", name:"Trilogy Metals", exchange:"NYSE Am USD", currency:"USD", shares:45.8082, average_cost:7.09, current_price:4.0, status:"watch", catalyst:"US DoW deal close pending", thesis:"US Dept of War binding LOI for 10% equity at $2.17/unit. South32 JV. Arctic drill season active June-Sept. FAST-41 pending.", exit_rule:"Hold. Do not add until US government deal officially closes." },
  { ticker:"TRX", name:"TRX Gold", exchange:"TSX CAD", currency:"CAD", shares:221.8014, average_cost:2.12, current_price:1.57, status:"add", catalyst:"Buckreef expansion + gold $3,300+", thesis:"Real gold producer. Record Q2: 7,453 oz at $4,655/oz. 62% gross margin. $25M cash. Zero warrants. $2.30 analyst target.", exit_rule:"Core position. Sell 25% at $2.30 CAD. Hold rest for $3+. Add on dip below $1.50." },
  { ticker:"USA", name:"Uranium Americas", exchange:"TSX-V CAD", currency:"CAD", shares:83.5204, average_cost:10.36, current_price:8.42, status:"watch", catalyst:"Uranium price + permitting", thesis:"Uranium at $84+/lb. Nuclear renaissance as AI data center power solution. Development stage with strong macro tailwind.", exit_rule:"Hold small position. Verify thesis on next company news release." },
  { ticker:"SVR", name:"iShares Silver ETF", exchange:"TSX CAD", currency:"CAD", shares:5, average_cost:19.214, current_price:37.0, status:"hold", catalyst:"Silver macro + industrial demand", thesis:"Physical silver. Industrial demand from solar, EVs, AI infrastructure. TFSA-eligible portfolio ballast.", exit_rule:"Hold. Add systematically while silver bull market remains intact." }
] as const;

export const seedWatchlist = [
  { ticker:"RDW", name:"Redwire Corporation", currency:"USD", current_price:20, entry_target:14.50, analyst_target:14.44, bull_target:28, thesis:"Space defense infrastructure. $498M backlog. 1.92 book-to-bill. NATO, DARPA, and US Army contracts. 57.9% revenue growth YoY. Wait for SpaceX IPO sentiment to cool.", why_not_bought:"Trading above analyst consensus. Entry at $14.50 gives better upside to bull case." },
  { ticker:"NOK", name:"Nokia", currency:"USD", current_price:15.47, entry_target:12.50, analyst_target:9.71, bull_target:18, thesis:"AI networking transformation. 49% AI/Cloud revenue growth Q1 2026. EUR 1B hyperscaler purchase orders. Optical Networks +20%.", why_not_bought:"Already ran hard from $4. Wait for pullback to $12.50." },
  { ticker:"XNDU", name:"Xanadu Quantum Technologies", currency:"USD", current_price:14, entry_target:11.50, analyst_target:44, bull_target:44, thesis:"First pure-play photonic quantum computing public company. Room temperature operation, DOE Oak Ridge partnership, and $302M raised at IPO.", why_not_bought:"Lock-up overhang creates volatility. Wait for $11.50." },
  { ticker:"JOBY", name:"Joby Aviation", currency:"USD", current_price:10, entry_target:8, analyst_target:11, bull_target:16, thesis:"Electric air taxi. FAA Stage 4 of 5 certification. Dubai commercial launch H2 2026. Toyota manufacturing partner and Uber integration.", why_not_bought:"Binary catalyst has not fired yet. Wait for $8 pullback." },
  { ticker:"AUR", name:"Aurora Innovation", currency:"USD", current_price:7, entry_target:5.50, analyst_target:6.50, bull_target:15, thesis:"Autonomous long-haul trucking. 250,000+ safe driverless commercial miles. McLane agreement, Hirschbach 500-truck MOU, 200+ driverless truck target.", why_not_bought:"Still pre-meaningful-revenue. Entry at $5.50 lowers risk." },
  { ticker:"SERV", name:"Serve Robotics", currency:"USD", current_price:8.85, entry_target:6, analyst_target:12, bull_target:18, thesis:"NVIDIA-backed delivery and hospital robots. Q1 2026 revenue up 578% YoY. 2,000 robots deployed. $197M cash.", why_not_bought:"Shelf and ATM dilution risk. Wait for $6." },
  { ticker:"SOUN", name:"SoundHound AI", currency:"USD", current_price:8.29, entry_target:6.50, analyst_target:14, bull_target:20, thesis:"Voice AI and agentic AI platform. Revenue +52% YoY. Casey's, Qualitas, OASYS platform, LivePerson acquisition pending.", why_not_bought:"CFO departure adds uncertainty. Wait for $6.50." },
  { ticker:"POET", name:"POET Technologies", currency:"USD", current_price:15, entry_target:10, analyst_target:null, bull_target:30, thesis:"Optical Interposer solves AI server bandwidth bottleneck. $500M Lumilens deal, institutional buy at $21, Malaysia expansion, 2027 production ramp.", why_not_bought:"Lawsuit and CFO retirement. $10 is discipline point." },
  { ticker:"SMR", name:"NuScale Power", currency:"USD", current_price:11, entry_target:9, analyst_target:19, bull_target:35, thesis:"Only NRC-approved SMR design in the US. $1.2B cash, zero debt. TVA PPA is the binary catalyst.", why_not_bought:"Revenue tiny and TVA timing uncertain. Wait for $9." },
  { ticker:"MP", name:"MP Materials", currency:"USD", current_price:67, entry_target:55, analyst_target:81, bull_target:100, thesis:"Only integrated rare earth producer in Western Hemisphere. Apple, GM, US DoW customers. Magnet revenue H2 2026 is the catalyst.", why_not_bought:"Above preferred range. Wait for $55 pullback." },
  { ticker:"BTC", asset_type:"crypto", coin_gecko_id:"bitcoin", name:"Bitcoin", currency:"USD", current_price:103000, entry_target:85000, analyst_target:null, bull_target:109000, catalyst:"CLARITY Act signing before July 4", thesis:"Digital gold. ETF inflows, fixed 21M supply, and institutional adoption. CLARITY Act opens more institutional floodgates.", why_not_bought:"Wait for $85,000 or a policy-driven setup." },
  { ticker:"SOL", asset_type:"crypto", coin_gecko_id:"solana", name:"Solana", currency:"USD", current_price:170, entry_target:130, analyst_target:null, bull_target:293, catalyst:"CLARITY Act plus SOL ETF approval", thesis:"Fast layer-1 with low fees and consumer crypto traction. ETF applications filed. Commodity classification would help.", why_not_bought:"Wait for $130." },
  { ticker:"ETH", asset_type:"crypto", coin_gecko_id:"ethereum", name:"Ethereum", currency:"USD", current_price:2500, entry_target:2000, analyst_target:null, bull_target:4878, catalyst:"RWA tokenization and staking ETF", thesis:"Smart contract backbone with BlackRock BUIDL, staking yield, and ETF adoption.", why_not_bought:"Wait for $2,000." },
  { ticker:"XDC", asset_type:"crypto", coin_gecko_id:"xdce-crowd-sale", name:"XDC Network", currency:"USD", current_price:0.035, entry_target:0.025, analyst_target:null, bull_target:0.193, catalyst:"DTCC October 2026 plus CLARITY Act", thesis:"Enterprise blockchain for trade finance. Contour acquisition and regulatory-friendly design.", why_not_bought:"Wait for $0.025." }
] as const;

export const seedCatalysts = [
  { ticker:"SLS", title:"SLS REGAL Readout", description:"78/80 events recorded as of May 11. CEO publicly stated very good chance GPS beats earlier survival outcomes. Hold all 200 shares.", source:"manual", severity:"watch" },
  { ticker:"PNG", title:"PNG Kraken Robotics Earnings", description:"First post-Covelya earnings. $52M orders YTD. $10.80 analyst target vs $7.69. Strong equals add. Weak equals reassess.", event_date:"2026-06-03", source:"manual", severity:"watch" },
  { ticker:"CLARITY", title:"CLARITY Act Senate Floor Vote", description:"Congress returns June 2. White House targeting July 4 signing. Direct catalyst for CAN, XRP, HBAR and crypto exposure.", event_date:"2026-07-04", source:"manual", severity:"good" },
  { ticker:"BB", title:"BlackBerry Earnings", description:"QNX plus NVIDIA in focus. Strong beat equals hold/add. Miss equals take profit.", event_date:"2026-06-25", source:"manual", severity:"watch" },
  { ticker:"CAN", title:"CAN NASDAQ Deadline", description:"Stock must hold $1.00+ for 10 consecutive days. Exit plan set if it fails.", event_date:"2026-07-13", source:"manual", severity:"bad" },
  { ticker:"FDY", title:"FDY BHP Definitive Deal", description:"BHP signs definitive agreement. Q3 target window for San Manuel re-rating event.", event_date:"2026-09-30", source:"manual", severity:"good" },
  { ticker:"GRSL", title:"GRSL Maiden PEA", description:"Late 2026 economic study decision gate after best-ever drill results.", event_date:"2026-12-31", source:"manual", severity:"good" },
  { ticker:"TMQ", title:"TMQ US DoW Deal Close", description:"US Dept of War LOI for 10% equity. Close equals government validation.", source:"manual", severity:"good" }
] as const;

export const seedRules = [
  "Sell only when the thesis breaks, your price target hits, or a better opportunity requires the capital. Not because you are bored.",
  "Before every purchase, write why you are buying and what has to happen for you to sell. If you cannot write both, do not buy.",
  "TFSA first, always. Every contribution goes into TFSA until the room is filled.",
  "When any position doubles: sell 25%, hold 75%. Lock some gain and let the thesis run.",
  "AMC exit ladder is binding: sell 1,000 at $3, 1,000 at $5, 1,223 at $6.50. Do not cancel the plan emotionally.",
  "INFQ.WS and XNDU are 18-24 month holds minimum unless the thesis breaks.",
  "The shiny stock test: before buying anything new, ask whether it is better than adding to TRX right now.",
  "Sublime Creations is the best investment. Protect the business engine first."
] as const;
